# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bfe21211ca97d33ece5276d93c3b311746345da82396f54306057ef5c3d2a380f8d28b7e67ebea2f90c8e4a6bd26dbbd741cdb5df0dbf9ed614017b16649415

test:
  secret_key_base: 6baed600e700d9a6b36f48b264566d68ca996fb740199a382677fd389011ae0d2e8935d7869688fb087af6d33b489e5f8fbe33391951d8cf8d1799aab5f9bd46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
